name: GitHub Contribution summary
description: Generates a summary of your GitHub contributions
branding:
  icon: book
  color: blue

inputs:
  token:
    description: GitHub.com token for authentication.
    required: true
  emuTokens:
    description:
      A comma-separated list of additional GitHub tokens for authentication.
      These are used to authenticate to GitHub Enterprise Cloud - Enterprise
      Managed User instance(s).
    required: true
  numberOfDays:
    description: The number of days to look back. Defaults to 14.
    required: false
  owner:
    description:
      The owner (user or organization) to create the summary issue in.
    required: false
  repository:
    description: The repository to create the summary issue in.
    required: true
  projectNumber:
    description: The project to create the summary issue in.
    required: true

runs:
  using: node20
  main: dist/index.js
